### ISSUE TITLE
Comments API

### ISSUE THREAD

**Issue by ok2ju** [futturum/node-interviewr#14]
after comment request, we need to save user data (author of comment) in array of comments.

Collection must looks like this (info about user we cat take from token):

comments: [{
 createdAt: new Date(),
 name: 'string',
 surname: 'string',
 id: ref to User,
 text: 'string'
}]

**Comment by Atsman** [comment]
comments: [{
    userId: mongoose.Schema.Types.ObjectId,
    createdAt: Date,
    text: String
  }]
